### PR TITLE
[CLOUD-3608] Publish EAP XP 1.0 ImageStreams and Templates

### PR DESCRIPTION
**Pull request by jmesnil**
JIRA: https://issues.redhat.com/browse/CLOUD-3608

Signed-off-by: Jeff Mesnil <jmesnil@redhat.com>

### CODE REVIEW

**Comment by jmesnil** [comment]
@mchoma Could you please review and approve?
The content is identical to the development branch at https://github.com/jboss-container-images/jboss-eap-openshift-templates/tree/eap-xp1-dev

**Comment by mchoma** [comment]
They are not same 

- 
```
diff eap-xp1/jboss-eap-openshift-templates/templates/eap-xp1-basic-s2i.json eap-xp1-dev/jboss-eap-openshift-templates/templates/eap-xp1-basic-s2i.json
70d69
<             "value": "jaxrs-server",
```
- Also I see README.md in this MR compared to eap-xp1-dev

**Comment by jmesnil** [comment]
@mchoma my mistake, I copied the content without removing the existing README.MD and was not on the tip of eap-xp1-dev. I've fixed the PR

**Comment by mchoma** [comment]
I approve.

This merge request is identical with was was tested during XP1 work.
This MR comes in expected timeframe during XP1 work .

Thanks for letting me know.

**Review by mchoma — APPROVED** [review]

**Review by luck3y — APPROVED** [review]

**Pull request merged**
