### PR TITLE
JBEAP-18682 - update AMQ version to 7.5 and correct imagestream name

### PR DESCRIPTION
**Pull request by luck3y**
https://issues.redhat.com/browse/JBEAP-18682
Signed-off-by: Ken Wills <kwills@redhat.com>

### CODE REVIEW

**Review by jmesnil — APPROVED** [review]
unrelated to your PR but if AMQ can get rid of the `-openshift`, we should check if we could do the same for our images and remove the `-openshift-rhel8`...

**Comment by luck3y** [comment]
> unrelated to your PR but if AMQ can get rid of the `-openshift`, we should check if we could do the same for our images and remove the `-openshift-rhel8`...

+1 yeah. The reason for that is historical, AFAIK we can name imagestreams whatever we like.

**Comment by jmesnil** [comment]
I was actually talking about the actual image names (not their imagestreams):

AMQ Broker image is [registry.redhat.io/amq7/amq-broker:7.5](https://catalog.redhat.com/software/containers/amq7/amq-broker/5d1cdce45a134672890c73d4?tag=7.5&push_date=1582022250000) so that'd be great if (future) EAP images could be named `jboss-eap7/eap-openjdk11:7.4` :)

**Comment by luck3y** [comment]
> I was actually talking about the actual image names (not their imagestreams):
> 
> AMQ Broker image is [registry.redhat.io/amq7/amq-broker:7.5](https://catalog.redhat.com/software/containers/amq7/amq-broker/5d1cdce45a134672890c73d4?tag=7.5&push_date=1582022250000) so that'd be great if (future) EAP images could be named `jboss-eap7/eap-openjdk11:7.4` :)

Ah, right yeah. I think we'd have to check some apps and maybe ask Chris if this is doable, for those images I'm pretty sure -openshift and -rhelX are being added automatically in comet.

**Pull request merged**
