### PR TITLE
[JBEAP-23324] Fix warning due to incorrect value of ImageStream and T…

### PR DESCRIPTION
**Pull request by mackaypeter**
…emplate apiVersion.

Issue: https://issues.redhat.com/browse/JBEAP-23324

### CODE REVIEW

**Review by soul2zimate — APPROVED** [review]

**Comment by yselkowitz** [comment]
The imagestreams look fine, but templates typically contain multiple objects, each of which need to be handled, e.g. Route's v1 => route.openshift.io/v1 etc.  Those APIs (e.g. Service) which are documented as core/v1 stay as "v1".

**Review by jmesnil — CHANGES_REQUESTED** [review]
@mackaypeter could you please update this PR based on @yselkowitz feedback?
The changes should be aligned with what @soul2zimate did in #43

**Comment by luck3y** [comment]
@mackaypeter Any update on this? Thanks!

**Comment by yselkowitz** [comment]
Ping?

**Comment by mackaypeter** [comment]
Updated the PR. I'll run a quick test, and then this can be merged.

**Review by jmesnil — APPROVED** [review]

**Pull request merged**
