### PR TITLE
Update SSO to 7.5

### PR DESCRIPTION
**Pull request by yselkowitz**

### CODE REVIEW

**Review by jmesnil — APPROVED** [review]

**Comment by yselkowitz** [comment]
@jmesnil this needs to be merged urgently, since samples for old versions of SSO have been removed from library.

**Comment by mackaypeter** [comment]
We didn't see any issues when testing the update, so this can be merged.

**Comment by mackaypeter** [comment]
We didn't see any issues when testing the update, so this can be merged.

**Review by mackaypeter — APPROVED** [review]

**Comment by jmesnil** [comment]
@yselkowitz @mackaypeter thanks!

**Pull request merged**
