### PR TITLE
[CLOUD-3918] - EAP 7.4.0.Beta Release Imagestreams and templates

### PR DESCRIPTION
**Pull request by jmesnil**
Put back the missing eap74-beta-starter-s2i.json template

Signed-off-by: Jeff Mesnil <jmesnil@redhat.com>

### CODE REVIEW

**Comment by jmesnil** [comment]
@luck3y I did a diff with the existing basic template and the only actual changes are the resources (services, env vars) related to MQ and Clustering.

**Review by luck3y — APPROVED** [review]

**Comment by mchoma** [comment]
I can confirm our test is passing with this template.

**Comment by jmesnil** [comment]
@mchoma are you checking the presence of the template or verifying that it can deploy an app on OpenShift Online Started Edition?

**Comment by mchoma** [comment]
> @mchoma are you checking the presence of the template or verifying that it can deploy an app on OpenShift Online Started Edition?

I am checking deploy of app on OpenShift (Not `OpenShift Online Started Edition`)

**Comment by mchoma** [comment]
Are you going to merge this?

**Comment by luck3y** [comment]
Yep :)

**Pull request merged**
